function config($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise("/home/index");
    $stateProvider
        .state("home",{
            url:"/home",
            templateUrl:"view/content.html"
        })
        .state("home.index",{
            url:"/index",
            templateUrl:"view/index.html",
            data:{
                'title':"wanglin",
                'data':[1,2,3,4,5]
            },
            controller:'index'
        })
        .state("home.list",{
            url:"/list",
            templateUrl:"view/list.html",
            data:[1,2,3,4,5,6],
            controller:'list'
        })
        .state("home.pro",{
            url:"/pro",
            templateUrl:"view/pro.html",
            controller:'pro'
        })
        .state("home.about",{
            url:"/about?id&name",
            templateUrl:"view/about.html",
            controller:'about'
        })
        .state("user",{
            url:"/user",
            templateUrl:"view/content2.html"
        })
        .state("user.info",{
            url:"/info",
            templateUrl:"view/info.html"
        })
}
angular.module("app")
       .config(config)